### ISSUE TITLE
Support for PyTorch Lightning models

### ISSUE THREAD

**Issue by salman1993** [operatorai/modelstore#13]
Would it be possible to add support for PyTorch lightning models?

https://modelstore.readthedocs.io/en/latest/concepts/libraries.html#id11

The interface is quite simple:

```
model = MyLightningModule(hparams)
trainer.fit(model)
# save checkpoint
trainer.save_checkpoint("example.ckpt")

# load checkpoint
new_model = MyLightingModule.load_from_checkpoint(checkpoint_path="example.ckpt")
```

**Comment by nlathia** [comment]
Yep, I can look into getting that added in soon 🙏 

(PRs welcome as well!)

**Comment by nlathia** [comment]
👍 That's been added in. It will go out in `modelstore==0.0.5`; I'll bundle up some extra things I'm working on with this and release that soon. Thanks for the suggestion!
