### ISSUE TITLE
Model Store Path uses a : , which is a reserved character in Windows

### ISSUE THREAD

**Issue by cdknorow** [operatorai/modelstore#140]
The model store uses a: in the pathname as a convention. This causes an issue when copying the model store over to a windows machine. 

ie.
operatorai-model-store/c4d99af6-363a-4d57-8934-6f0af2e4c211/2022/02/22/21:20:22

fatal: cannot create directory at 'operatorai-model-store/c4d99af6-363a-4d57-8934-6f0af2e4c211/2022/02/22/21:20:22': Invalid argument

Fixing this would most likely be a breaking change, but it is probably worth doing that to maintain compatibility

**Comment by nlathia** [comment]
Oh, wow, thanks for reporting! It looks like there are [a few characters that are now allowed](https://docs.microsoft.com/en-gb/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#file_and_directory_names):

```
The following reserved characters:

< (less than)
> (greater than)
: (colon)
" (double quote)
/ (forward slash)
\ (backslash)
| (vertical bar or pipe)
? (question mark)
* (asterisk)
```

I'll investigate soon 👀
