### ISSUE TITLE
xgb.core.Booster object not supported

### ISSUE THREAD

**Issue by robertpknight** [operatorai/modelstore#169]
When trying to load a `xgb.core.Booster` object I get a `ValueError: could not find matching manager` error. So it appears this lower level xgboost object (which doesn't implement the sklearn API) is not currently supported.

**Comment by nlathia** [comment]
Thanks Rob! I'll get this reviewed soon

**Comment by nlathia** [comment]
Merged your PR - thanks for your contribution 🙏 

I've followed up in this PR where I'm adding more tests etc.

- https://github.com/operatorai/modelstore/pull/177

**Comment by nlathia** [comment]
✅  This was released as part of `modelstore==0.0.75`

- https://github.com/operatorai/modelstore/pull/201

Let me know if you see any other issues!
