### ISSUE TITLE
Run integration tests against actual modelstore instances

### ISSUE THREAD

**Issue by ionicsolutions** [operatorai/modelstore#175]
It would be super helpful to have modelstore instances on each of the supported cloud storage services that can be used for integration tests.

**Comment by smoothzebra** [comment]
Good

**Comment by nlathia** [comment]
Hi @ionicsolutions! I currently do have this, but the keys to each is private. One possibility would be to have public buckets, but that's somewhat risky too and doesn't allow us to test that modelstore can write to non-public buckets. Did you have anything else in mind?

**Comment by smoothzebra** [comment]
SHOULD COPPY DATABASE

**Comment by ionicsolutions** [comment]
> Hi @ionicsolutions! I currently do have this, but the keys to each is private. One possibility would be to have public buckets, but that's somewhat risky too and doesn't allow us to test that modelstore can write to non-public buckets. Did you have anything else in mind?

I was thinking about an integration test suite that runs through GitHub Actions. The bucket/project names and the keys to the private instances can be stored as repository secrets, so no one will have access to them.

I believe that running a simple sequence of "upload models", "list available domains", "list available models", "retrieve models", "delete models" that is executed for each storage backend would already provide a lot of added confidence. In my case, I was particularly interested in testing the read-only GCP access, where we don't need credentials for accessing it but just a prepared bucket with a few small models. In general, the models can be super small, so I don't think transfer costs should be an issue.

Let me know if I can assist you in setting this up.

**Comment by nlathia** [comment]
Thanks! I think this is a great idea overall. 

It's also fairly straightforward as I can re-purpose some of the [examples](https://github.com/operatorai/modelstore/tree/main/examples) code for this purpose.

I'll aim to set this up before the next release 🔜

**Comment by nlathia** [comment]
FYI @ionicsolutions I've been working on this PR ☝️ with the suggestion above. Not finished yet, but it shows what it will become: a set of actions that are run on all different model store storage types. Feedback welcome!

**Comment by nlathia** [comment]
This has now been merged, thank you for the suggestion @ionicsolutions! There's scope to improve it over time (there are some things it doesn't test yet)

- https://github.com/operatorai/modelstore/pull/186
