### ISSUE TITLE
Can I refactor your code into pyscaffold?

### ISSUE THREAD

**Issue by prassanna-ravishankar** [operatorai/modelstore#193]
I've used [Pyscaffold](https://pyscaffold.org/en/stable/) before to maintain structured python libraries. It offers 
1. Machinery over documentation
2. Best practices around `setup.cfg` instead of `setup.py`
3. Development builds (so I can do something like `pip install -e .[dev]`)
4. **Pre-commits**

In addition, I could
1. Set up workflows to push to `.whl` packages to GH (and optionally to pypi later)

**Comment by nlathia** [comment]
Hello, thanks! While I see the value that pyscaffold seems to offer, I have not used it myself (yet).

As the core maintainer of this library, my preference is to **not** accept a refactor of the library into a framework that I am not familiar with.

I will try to find some time to learn about it and will consider migrating this library to it if/when I do.

Thanks for the offer, though! You can find a lot of the open feature requests on the [discussions area](https://github.com/operatorai/modelstore/discussions)
