### ISSUE TITLE
colab notebook example error

### ISSUE THREAD

**Issue by eye0inc** [operatorai/modelstore#194]
Hi, great concept! Trying to get this example to work:

https://colab.research.google.com/drive/1yEY6wy68k7TlHzm8iJMKKBG_Pl-MGZUe?usp=sharing

All cells run fine  up to this one:

```
modelstore = ModelStore.from_gcloud(
    project_name=gcp_project_id,
    bucket_name=gcp_bucket_name
)

GCP project name: testmodstore
Cloud Storage bucket name: modstore

---------------------------------------------------------------------------

TransportError                            Traceback (most recent call last)

[/usr/local/lib/python3.7/dist-packages/google/auth/compute_engine/credentials.py](https://localhost:8080/#) in refresh(self, request)
    110         try:
--> 111             self._retrieve_info(request)
    112             self.token, self.expiry = _metadata.get_service_account_token(

17 frames

TransportError: ("Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\nb''", <google.auth.transport.requests._Response object at 0x7feb2aa2f110>)
```
Guidance appreciated!!

**Comment by nlathia** [comment]
👋 @eye0inc Thanks for raising this! I managed to replicate the error in your Colab notebook as well.

This seems to be due to Colab authentication. I tried adding a cell to your notebook to allow auth:

```
from google.colab import auth

auth.authenticate_user()
```

And then it worked 🙌 

The issue inside of the `modelstore` library is that it's trying to figure out if a user is in Colab [by catching a `DefaultCredentialsError`](https://github.com/operatorai/modelstore/blob/main/modelstore/storage/gcloud.py#L99-L107) and I'm wondering whether the behaviour of `google-cloud-storage` has changed.

The Colab environment is running `google-cloud-storage==1.18.1` while I had developed `modelstore` [using `google-cloud-storage>=2.3.0`](https://github.com/operatorai/modelstore/blob/main/requirements-dev1.txt#L8); so perhaps that is what the root problem is here. 

I would need to investigate more to see if there's anything in `modelstore` that needs changing, but for now if you add the two auth lines above you should be good to go 🚀

**Comment by eye0inc** [comment]
Hi, thanks for the response!

I added the oauth lines and that issue seems to be fixed. However now I get this error:
```
from modelstore import ModelStore

# Your GCP project name
gcp_project_id = input("GCP project name: ") 

# The name of the bucket where you want to store your ML models
gcp_bucket_name = input("Cloud Storage bucket name: ") 

modelstore = ModelStore.from_gcloud(
    project_name=gcp_project_id,
    bucket_name=gcp_bucket_name
)
```
---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

[/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py](https://localhost:8080/#) in _dep_map(self)
   3015         try:
-> 3016             return self.__dep_map
   3017         except AttributeError:

14 frames

AttributeError: _DistInfoDistribution__dep_map


During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)

AttributeError: _pkg_info


During handling of the above exception, another exception occurred:

FileNotFoundError                         Traceback (most recent call last)

[/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py](https://localhost:8080/#) in _get(self, path)
   1609 
   1610     def _get(self, path):
-> 1611         with open(path, 'rb') as stream:
   1612             return stream.read()
   1613 

FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/dist-packages/requests-2.23.0.dist-info/METADATA'
```

Sorry to be a pest but I really like this project and hope I can get it running.

**Comment by eye0inc** [comment]
That problem resolved with restart runtime but now:
```
Forbidden: 403 GET https://www.googleapis.com/storage/v1/b/modelstore?projection=noAcl: [dan.miller@eye0.com](mailto:dan.miller@eye0.com) does not have storage.buckets.get access to the Google Cloud Storage bucket.
```

So I guess I have to create that bucket & make it public? Or some permissions setting?

**Comment by nlathia** [comment]
Yep, currently modelstore assumes that the bucket exists (but it doesn't need to be public - you just need to have permissions to read and write to it); the library won't create the bucket of it is missing.

**Comment by eye0inc** [comment]
OK got much further:
```
 Add the model to your model store

model_domain = "diabetes-boosting-demo"
meta_data = modelstore.sklearn.upload(model_domain, model=reg)

TypeError                                 Traceback (most recent call last)

[<ipython-input-11-65ea786da45e>](https://localhost:8080/#) in <module>()
      1 model_domain = "diabetes-boosting-demo"
----> 2 meta_data = modelstore.sklearn.upload(model_domain, model=reg)

TypeError: upload() missing 1 required positional argument: 'model_id'
```

**Comment by nlathia** [comment]
Great! You no longer need to specify the upload type, so `modelstore.upload()` instead of `modelstore.sklearn.upload()` should work

**Comment by eye0inc** [comment]
Thanks! It works perfectly. I see the json metadata + the artifact in my gcp bucket...

Is there a preferred forum to discuss this project (so as not to pollute the issues board)? Also, should I submit a pull request with these changes?

Thanks again, great work.

**Comment by nlathia** [comment]
Pull requests welcome 😃

You can also find me here or in the #oss-modelstore channel of the MLOps Community slack:

https://go.mlops.community/slack
