### ISSUE TITLE
Using MinIO s3 buckets

### ISSUE THREAD

**Issue by lenoqt** [operatorai/modelstore#212]
It is possible to make this work with MinIO S3 buckets? I've been trying it up with no success, or do I have to write my own wrapper around ```AWSStorage``` ?

**Comment by nlathia** [comment]
Hello! There was a similar request here:

https://github.com/operatorai/modelstore/discussions/183

Happy to look into this! Any more details of how you use it would be welcome - are you using it over s3?

**Comment by lenoqt** [comment]
I am closing this and continuing the conversation there.
