### ISSUE TITLE
Add HDFS as a backend for modelstore

### ISSUE THREAD

**Issue by sayandigital** [operatorai/modelstore#232]

**Comment by nlathia** [comment]
Thanks for the suggestion @sayandigital! 

I was looking at the opinions [on stackoverflow](https://stackoverflow.com/questions/40285184/whats-the-best-module-for-interacting-with-hdfs-with-python3), and so thought I'd ask you: what's your preferred Python client for HDFS?

**Comment by sayandigital** [comment]
pydoop/pyhdfs

**Comment by nlathia** [comment]
Great, I'll add this in soon 🔜

**Comment by nlathia** [comment]
@sayandigital Sorry for the delay with this. I've started implementing it (there's a draft PR), I hope to have this finished asap

**Comment by nlathia** [comment]
This is now merged and will go out in the next release 🙏🏽 let me know if you see any issues!

**Comment by nlathia** [comment]
Released!
