### ISSUE TITLE
Transformers - Failure scenarios

### ISSUE THREAD

**Issue by sayandigital** [operatorai/modelstore#233]
https://huggingface.co/gpt2/tree/main

Here is how to use this model to get the features of a given text in PyTorch:

from transformers import GPT2Tokenizer, GPT2Model
tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
model = GPT2Model.from_pretrained('gpt2')
text = "Replace me by any text you'd like."
encoded_input = tokenizer(text, return_tensors='pt')
output = model(**encoded_input)

and in TensorFlow:(updated with config)

from transformers import GPT2Tokenizer, TFGPT2Model,PretrainedConfig
tokenizertf = GPT2Tokenizer.from_pretrained('gpt2')
model_tf = TFGPT2Model.from_pretrained('gpt2')
configtf=PretrainedConfig.from_pretrained('gpt2')
text = "Replace me by any text you'd like."
encoded_input = tokenizertf(text, return_tensors='tf')
outputtf = model_tf(encoded_input)

<img width="876" alt="image" src="https://user-images.githubusercontent.com/24439178/224896492-ea1e7aa2-9550-478a-8fd0-2cc9ca7ac68f.png">

        return kwargs["model"].optimizer.get_config() - Seems the optimizer is None

Both the model upload is failing to the modelstore

**Comment by nlathia** [comment]
Thanks @sayandigital - I've found one bug so far related to how `modelstore` decides to save models. Am working on it in the PR linked above, which includes the TF example you at the top of your issue.

**Comment by nlathia** [comment]
I've just merged the fix, this will go out in the next release of `modelstore` and I'll keep the issue open until then. Thanks again!

**Comment by nlathia** [comment]
Released!
