### ISSUE TITLE
Add an entrypoint to setup.py

### ISSUE THREAD

**Issue by nlathia** [operatorai/modelstore#252]
> Would be nice to add an entrypoint to the setup.py so you can use the CLI as modelstore --help instead of python -m modelstore --help (this is what im doing for our internal wrappers)

https://mlops-community.slack.com/archives/C0227QJCDS8/p1688628055056109?thread_ts=1687777412.934619&cid=C0227QJCDS8

**Comment by rladbrua0207** [comment]
I've implemented a solution for this issue and am planning to submit a PR shortly. Is that okay?

**Comment by nlathia** [comment]
> I've implemented a solution for this issue and am planning to submit a PR shortly. Is that okay?

Of course, thank you so much!
