### ISSUE TITLE
[Request] Add support for vowpal wabbit framework 

### ISSUE THREAD

**Issue by nambrosini17** [operatorai/modelstore#276]
See https://github.com/VowpalWabbit/vowpal_wabbit

**Comment by nlathia** [comment]
💡 Great idea! PRs are welcome if you are looking for a chance to contribute.

I've put together a [contributing guide](https://github.com/operatorai/modelstore/blob/main/modelstore/models/CONTRIBUTING.md) that is specific for adding support for new ML frameworks.
