### ISSUE TITLE
Versioning rasa models using modelstore ?

### ISSUE THREAD

**Issue by dingusagar** [operatorai/modelstore#52]
I am looking for versioning models for production generated by rasa framework. Came across this tool. Wanted to know if this is suitable for my use-case.

**Comment by nlathia** [comment]
Hi @dingusagar, just to double check: you are referring to this framework right? https://github.com/RasaHQ/rasa

It's currently not supported in this library, but we could look to add it in!

I've had a quick look at the Rasa docs, and found [loading models](https://rasa.com/docs/rasa/model-storage) but have only found the [command line guidance](https://rasa.com/docs/rasa/command-line-interface) for model training - are you training these models in a python script/can you point me to an example?

**Comment by dingusagar** [comment]
yes, this is the framework i was referring to. 
i train my project using command line. (rasa train)
but if we want we can even invoke it from a python script since the whole framework is written python.

for eg:
`from rasa.cli.train import run_training
run_training(args=args)`

**Comment by dingusagar** [comment]
In rasa, once you do the training, a compressed model file is created (a tar.gz file ). 
If there is any way to simply pass on this file path to modelstore along with some optional metadata if requried, that would be good enough. 


something like
```
domain = "example-model"
meta_data = model_store.upload(domain, model="sample-project/models/rasa-trained-model.tar.gz")
```

and model download like

```
model_path = model_store.download(
   local_path=target,
   domain=model_domain,
   model_id=meta["model"]["model_id"],
)
```
if it makes sense, i would be happy to help and contribute to this feature.

**Comment by nlathia** [comment]
Sounds good! I've started adding it in to the PR linked above - I had actually also been given this feedback by someone else via email as well, so I'm happy to do it 😄

**Comment by nlathia** [comment]
✅ This is now merged. Let me know if you get a chance to try it out, @dingusagar. You'll need to install from here rather than via pypi - as I haven't released this yet.

**Comment by dingusagar** [comment]
Thanks, will definitely check this out.

**Comment by nlathia** [comment]
Great - feel free to reopen this issue if you find any problems
